# Generated by Django 5.0.6 on 2024-07-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='content',
        ),
        migrations.AddField(
            model_name='version',
            name='uploaded_file',
            field=models.FileField(default='default/path/to/file.txt', upload_to='versions/'),
            preserve_default=False,
        ),
    ]
